name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        distribution: [ 'zulu' ]
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v3
      - name: Use JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew build
        env:
          GH_PACKAGES_READ_TOKEN: ${{ secrets.GH_PACKAGES_READ_TOKEN }}
          GH_PACKAGES_USER: ${{ secrets.GH_PACKAGEs_USER }}